# Describes the format for available remote services


send_command:
  target:
    entity:
      domain: sensor
  fields:
    command:
      required: true
      example: "setMachineState"
      selector:
        object:
    capability:
      required: true
      example: "ovenOperatingState"
      selector:
        object:  
    action:
      required: false
      example: "stop"
      selector:
        object:              

